### ISSUE TITLE
Csomag letöltése sikertelen

### ISSUE THREAD

**Issue by adrianmihalko** [Blindspot76/e2iPlayer#7]
Szia,

Több verziót is próbáltam, de mindegyiknél, ugyanaz a hiba: első indításkor próbálja letölteni az extra csomagokat (wget, rtmpdump stb.), de valamilyen régi szerverről próbálja, ezért kiírja, hogy letöltés sikertelen. Frissíteni sem tudom a programból ezen okból.

**Comment by Blindspot76** [comment]
Szia!  Próbáld meg TELJESEN eltávolítani a plugint a bővítménykezelőből. Ha így telepíted az ipk-t, pontosan mit nem tud letölteni.?
Egyes függőségek a méreteik miatt nincsenek a programban. Ezeket részben az adott image feedjéről az extensions menüből lehet letölteni (deps). Az FFMPEG és a PYCURL szintén nem a csomag részei, ezekhez a fórumban többször publikáltunk linket, onnan letölthetőek és telepíthetőek. (TelNet)
Üdv.

**Comment by adrianmihalko** [comment]
Szia,

VTI firmwaret használtam, az nem kompatibilis az e2iplayerrel. OpenATV alatt tökéletesen működik.

Üdv,
A

**Comment by adrianmihalko** [comment]
Kivéve egy dolgot: képtelen vagyok belépni egy másik (rtl most pluszos) fiókba. Jelszó tuti jól van beírva, többször ellenőriztem. Nem lehet ezt valahogy debuggolni?

**Comment by Blindspot76** [comment]
A plugin jelen formájában nem támogatja az RTL Most+-t, csak a sima
login/password működik.
Nem a player frissítésén múlik, az alkalmazott protokollt nem támogatja
(még) az ffmpeg.
Üdv.


adrianmihalko <notifications@github.com> ezt írta (időpont: 2020. okt. 2.,
P, 19:19):

**Comment by adrianmihalko** [comment]
Köszönöm.  👍
